CREATE TABLESPACE User19Ts
DATAFILE 'C:/bizwork/workspace/oracledata/user19.dbf'
SIZE 1M AUTOEXTEND ON NEXT 10K;

CREATE USER user19 IDENTIFIED BY user19
DEFAULT TABLESPACE user2TS;

GRANT DBA TO user19;